version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Clone UE4"
          shell: powershell.exe
          command: |
            echo "------------------------------"
            ls 
            pwd
            echo "-------------------------------"
            echo "Start Clone"
            git clone 4772db6e59cdcebbfc3185738a63f9c2c2ca83f1@https://github.com/EpicGames/UnrealEngine.git 
      - run:
          name: "Build UE4"
          shell: powershell.exe
          command: |
            echo "Start Build"
            cd UnrealEngine
            ./Setup.bat
            ./GenerateProjectFiles.bat
               